FROM openjdk:8-jdk

VOLUME /tmp
ADD anodot-daily-kpi.jar /opt/anodot-daily-kpi/
EXPOSE 8080
WORKDIR /opt/anodot-daily-kpi/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "anodot-daily-kpi.jar"]
